# action.yaml
name: "My Custom Github Action that runs OSSF Scorecard"
description: "Call an API and get the result"
outputs:
  pokemon_name:
    description: "Name des Pokemons"
runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      with:
        persist-credentials: false

    - name: "Run analysis"
      uses: ossf/scorecard-action@3e15ea8318eee9b333819ec77a36aca8d39df13e # tag=v1.1.1
      with:
        results_file: results.sarif
        results_format: sarif

    # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
    # format to the repository Actions tab.
    - name: "Upload artifact"
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
