name: SLSA3 Builder internal wrapper
description: SLSA3 Builder internal wrapper

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a JSON map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true

  slsa-workflow-secret1:
    description: 'secret1 is unused'
    type: string
    required: false

  slsa-workflow-secret2:
    description: 'secret2 is unused'
    type: string
    required: false

runs:
  using: 'composite'
  steps:
    # NOTE: the repository is already cloned by the caller, so there's no need to
    # checkout ourselves.

    # This calls the main action, e.g.,
    # ./../__TOOL_CHECKOUT_DIR__/<path/to/action> if path is left empty, the
    # action's action.yml is located at the root of the repository.
    - name: Run main Action
      uses: ./../__TOOL_CHECKOUT_DIR__

    # NOTE: Here we create a JSON file that describes the attestations we want
    #       to create. Each attestation will be created as a separate file,
    #       each with the subjects specified. This allows complicated release
    #       pipelines that output many artifacts to organize the attestations
    #       for those artifacts in a flexible way.
    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        UNTRUSTED_OUTPUT_FILE: results.sarif
      shell: bash
      run: |
        ./../__TOOL_ACTION_DIR__/generate-layout.sh "${UNTRUSTED_OUTPUT_FILE}" | tee "$SLSA_OUTPUTS_ARTIFACTS_FILE"
