name: SLSA3 Builder

permissions: {}

on:
  workflow_call:
    # NOTE: You need to maintain the defaults here as well as your main
    # action.yml
    inputs:
      # NOTE: the additional inputs below are to support additional
      # functionality of the workflow.
      rekor-log-public:
        description: 'Allow publication of your repository name on the public Rekor log'
        required: false
        type: boolean
        default: false

jobs:
  slsa-setup:
    permissions:
      id-token: write # For token creation.
    outputs:
      slsa-token: ${{ steps.generate.outputs.slsa-token }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate the token
        id: generate
        # TODO(github.com/ianlewis/slsa-byob-template/issues/11): Update version once released.
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-token@main
        with:
          slsa-workflow-recipient: 'delegator_lowperms-generic_slsa3.yml'
          slsa-rekor-log-public: ${{ inputs.rekor-log-public }}
          slsa-runner-label: 'ubuntu-latest'
          slsa-build-action-path: './internal/action-wrapper'
          # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/1575): mask sensitive fields.
          slsa-workflow-inputs: ${{ toJson(inputs) }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      # actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_lowperms-generic_slsa3.yml@v1.6.0
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}


  slsa-publish:
    needs: [slsa-run]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # For asset uploads. Optional
    runs-on: ubuntu-latest
    steps:
      - name: Download attestations
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.slsa-run.outputs.attestations-download-name }}

      - name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ inputs.file }}
